server:
  port: 8080
spring:
  application:
    name: rest-emulator
  kafka:
    bootstrap-servers: localhost:9092
    topic: "postedmessages"
    max:
      block:
        ms: 15000
    retries: 1
message:
  id:
    name: "msg_id"
