server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emulator
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  application:
    name: server-emulator
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    topic: "postedmessages"
management:
  endpoints:
    jmx:
      exposure:
        include:*
    web:
      exposure:
        include: prometheus,metrics,health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
    tags:
      application: server-emulator
  prometheus:
    metrics:
      export:
        enabled: true
